; SPDX-License-Identifier: EPL-2.0
(ns examples.gsot.22-ramp-div-musical
  "GSOT pp.48-49 — go.ramp.div in musical context: note-value subdivisions.

  'Musically relevant divisions'
  --------------------------------
  The pages apply go.ramp.div (example 21) to a beat ramp generated by
  go.ramp.frombpm (example 12), showing how integer division values map to
  standard Western note-value relationships:

      div=1  → beat ramp unchanged          (quarter note at 4/4)
      div=2  → half-time; one cycle per 2 beats  (half note)
      div=3  → triplet feel; one cycle per 3 beats (dotted quarter, or bar of 3)
      div=4  → one cycle per 4 beats        (whole note / one measure at 4/4)
      div=6  → one cycle per 6 beats        (dotted half in compound meter)
      div=8  → one cycle per 8 beats        (double-whole note / 2 bars)

  The musically relevant divisors are small integers that correspond to
  common note values and metric levels.  Irrational or large values produce
  polyrhythmic relationships; the section focuses on the integer cases that
  align with standard notation.

  Signal flow
  -----------
  This example chains the two utilities shown in the chapter:

      go.ramp.frombpm → beat-ramp → go.ramp.div → divided-ramp

      BPM + beats → measure phasor
                  → * beats → wrap 0 1       beat-ramp  [0,1) per beat
                  → go.ramp.div(N)            divided    [0,1) per N beats

  The measure ramp is also output so that the slow ramp and the driving
  clock are both available as patch outputs.

  go.ramp.div applied to the beat ramp
  --------------------------------------
  In the maxpat on pp.48-49, the beat ramp from go.ramp.frombpm feeds
  directly into go.ramp.div.gendsp.  The division param (integer N) selects
  the note-value level.  The result is a ramp that completes one cycle per
  N beats — suitable as a sequencer advance clock, an envelope trigger
  period, or a loop-length reference.

  Implementation note: counter max
  ----------------------------------
  The counter inside go.ramp.div is capped at 1024 (see example 21).  For
  musically relevant N ≤ 8 at any practical tempo, the cap is never reached
  within a session — the beat count before counter overflow at 1024 triggers
  is 1024/N ≥ 128 measures.

  Emitted Faust DSP
  -----------------
      import(\"stdfaust.lib\");

      n0 = hslider(\"bpm\", 120.0, 20.0, 300.0, 0.028);
      n1 = 60.0;
      n2 = (n0 / n1);
      n3 = hslider(\"beats\", 4.0, 1.0, 16.0, 0.0015);
      n4 = floor(n3);
      n5 = (n2 / n4);
      n6 = os.phasor(1.0, n5);
      n7 = (n6 * n4);
      n8 = 0.0;
      n9 = 1.0;
      n10 = (n8 + fmod((n7 - n8), (n9 - n8)));
      n11 = (n10 - n10');
      n12 = abs(n11);
      n13 = 0.5;
      n14 = (float(n12 > n13));
      n16 = hslider(\"div\", 2.0, 1.0, 8.0, 0.0007);
      n17 = floor(n16);
      n18 = 0.0;
      n19 = (select2(n18 > 0.5, select2((n14 > 0.5) & (n14' <= 0.5), _, fmod(_ + 1.0, 1024.0)), 0.0) ~ _);
      n21 = 0.0;
      n22 = (n21 + fmod((n19 - n21), (n17 - n21)));
      n23 = (n22 + n10);
      n24 = (n23 / n17);

      process = n24, n10, n6;"
  (:require [alembic.patch :refer [defpatch!]]))

(defpatch! ramp-div-musical
  {:params {:bpm   {:range [20.0 300.0] :default 120.0 :unit :bpm}
            :beats {:range [1.0 16.0]   :default 4.0   :unit :beats}
            :div   {:range [1.0 8.0]    :default 2.0}}}
  (let [;; go.ramp.frombpm — measure and beat ramps
        bpm-hz  (div (param :bpm) (const 60.0))
        beats   (floor (param :beats))
        hz      (div bpm-hz beats)
        measure (phasor hz)
        beat    (wrap (mul measure beats) (const 0.0) (const 1.0))
        ;; go.ramp.div — divide the beat ramp by N
        d       (delta beat)
        cmp     (comparator (abs d) (const 0.5))
        trig    (:out cmp)
        n       (floor (param :div))
        cnt     (counter {:max 1024 :dir :up :wrap true} trig (const 0.0))
        count   (wrap (:out cnt) (const 0.0) n)
        divided (div (add count beat) n)]
    (output :divided divided)
    (output :beat    beat)
    (output :measure measure)))
