; SPDX-License-Identifier: EPL-2.0
(ns examples.gsot.83-shift-register-weighted-xor
  "GSOT pp.131-132 — shift-register-weighted-xor.maxpat.

  'Evolving loops' (Chapter 5)
  ----------------------------
  A binary shift register where the new bit is generated by XOR feedback
  from specific tap positions (an LFSR), optionally mixed with random bits
  controlled by a weight parameter.

  Linear Feedback Shift Register (LFSR)
  --------------------------------------
  A maximal-length LFSR over 8 stages produces a pseudo-random sequence of
  period 255 — every non-zero 8-bit state appears exactly once before the
  sequence repeats.  The feedback polynomial x^8+x^4+x^3+x^2+1 uses taps
  at bit positions 7, 3, 2, 1 (0-indexed from LSB):

      lfsr_bit = (state[7] XOR state[3] XOR state[2] XOR state[1])

  The 'evolving loops' character: the 255-step LFSR sequence repeats
  exactly, creating a loop.  Injecting random bits (weight < 1.0) perturbs
  the state, pushing the LFSR into a different 255-step orbit — the same
  internal structure but a different phrase each time noise kicks in.

  Weight parameter
  ----------------
  :weight controls the probability that the new bit comes from the LFSR
  feedback rather than a random draw:

    weight=1.0 → pure LFSR: deterministic 255-step repeating loop
    weight=0.5 → 50/50 mix: occasionally perturbed, slowly drifts between orbits
    weight=0.0 → pure random: same as shift-register-weighted (example 81) at 0.5

  Architecture: packed integer state
  ------------------------------------
  The 8-stage shift register is encoded as a SINGLE 8-bit integer held in
  one ~ feedback register.  This avoids the cycle that would arise if each
  stage were a separate track-hold node (s0 would depend on the new bit,
  which depends on s7, which depends on s0 — a DAG cycle).

  State update on each trigger:
      lfsr_bit   = (state>>7)^(state>>3)^(state>>2)^(state>>1) & 1
      new_bit    = select2(rand < weight, random_0_or_1, lfsr_bit)
      new_state  = ((state>>1) | (new_bit<<7)) & 255

  Bit 7 of state is the newest (just entered); bit 0 is the oldest (about
  to be shifted out).  The & 255 masks to 8 bits.

  The two no.noise instances in the expression are separate Faust LCG
  registers (independent random streams), same mechanism as example 62.

  Zero state and initial conditions
  ------------------------------------
  The packed state initialises at 0.  With weight=1.0 (pure LFSR), the
  XOR of all-zero taps is 0, and the register stays all zeros indefinitely
  (0x00 is the LFSR's forbidden state).  Any weight < 1.0 ensures random
  bits populate the register after the first few triggers; weight=0.9
  gives almost-pure LFSR behaviour with occasional random escapes from 0.

  Outputs
  -------
  :s0 — newest bit (bit 7 of state; most recently entered)
  :s1 — one step older (bit 6)
  ...
  :s7 — oldest bit (bit 0; about to be shifted out on next trigger)

  Emitted Faust DSP:
      import(\"stdfaust.lib\");

      alembic_dsp(n0) = n_s0,...,n_s7
        with {
          n_wt = hslider(\"weight\", 0.5, 0.0, 1.0, 0.001);
          n_st = (select2(n0>0.5,_,
                    (((_>>1)|(select2(0.5*(no.noise+1.0)<n_wt,
                                     int(0.5*(no.noise+1.0)+0.5),
                                     ((_>>7)^(_>>3)^(_>>2)^(_>>1))&1)
                             <<7))&255))~_;
          n_s0 = float((int(n_st)>>7)&1);
          n_s1 = float((int(n_st)>>6)&1);
          ...
          n_s7 = float(int(n_st)&1);
        };
      process = alembic_dsp;"
  (:require [alembic.patch :refer [defpatch!]]))

(defpatch! shift-register-weighted-xor
  {:params {:weight {:range [0.0 1.0] :default 0.5}}}
  (let [trig   (audio-in)
        weight (param :weight)
        ; Packed 8-bit LFSR state in a single ~ register.
        ; Taps at bits 7,3,2,1 (polynomial x^8+x^4+x^3+x^2+1, period 255).
        ; new_bit = LFSR tap or random, chosen by weight.
        ; Two no.noise instances = two independent LCG registers.
        state  (faust "(select2(%tr>0.5,_,float(((int(_)>>1)|(select2(0.5*(no.noise+1.0)<%wt,int(0.5*(no.noise+1.0)+0.5),((int(_)>>7)^(int(_)>>3)^(int(_)>>2)^(int(_)>>1))&1)<<7))&255)))~_"
                      {:tr trig :wt weight})
        ; Extract individual bits: s0 = newest (bit 7), s7 = oldest (bit 0)
        s0 (faust "float((int(%st)>>7)&1)" {:st state})
        s1 (faust "float((int(%st)>>6)&1)" {:st state})
        s2 (faust "float((int(%st)>>5)&1)" {:st state})
        s3 (faust "float((int(%st)>>4)&1)" {:st state})
        s4 (faust "float((int(%st)>>3)&1)" {:st state})
        s5 (faust "float((int(%st)>>2)&1)" {:st state})
        s6 (faust "float((int(%st)>>1)&1)" {:st state})
        s7 (faust "float(int(%st)&1)"      {:st state})]
    (output :s0 s0)
    (output :s1 s1)
    (output :s2 s2)
    (output :s3 s3)
    (output :s4 s4)
    (output :s5 s5)
    (output :s6 s6)
    (output :s7 s7)))
